### PR TITLE
Adds all the endpoints available in the API

### PR DESCRIPTION
**Pull request by thispsj**
This PR incorporates a detailed documentation on Supercell ID API. I've tried to document as much as possible.

Also I've moved the API documentation in another Markdown file in order to ensure that README doesn't grow big.

Please note, I've not updated the PHP code. If you want to update that please tell me so that I will tick the "Allow edits by maintainers" box and you can add those endpoints to PHP.

### CODE REVIEW

**Comment by thispsj** [comment]
@ZeroBone I've enabled "Allow edits by maintainers" you can now directly add the code in my branch.

**Comment by ZeroBone** [comment]
@thispsj thanks for your contribution, everything looks good. Sorry for the delay.

**Comment by thispsj** [comment]
> @thispsj thanks for your contribution, everything looks good. Sorry for the delay.

@ZeroBone no need to be sorry. It's ok.

Actually I thought you were busy implementing the new endpoints in your PHP code and wanted to commit them on this branch 😅

**Comment by thispsj** [comment]
Also @ZeroBone I forgot to inform you that although `https://ingame.id.supercell.com` is still functional, all Supercell apps now use a different root endpoint.

**Pull request merged**
