### PR TITLE
Update APIDoc.MD

### PR DESCRIPTION
**Pull request by LaptopCat**
update the root url

### CODE REVIEW

**Comment by thispsj** [comment]
Hi @LaptopCat,

Ik that's the new root endpoint. But you know that that's the v2 API and it has more endpoints than what we currently have. That's why I have specified v1 root url although I know that it's no longer used by Supercell Games.

**Comment by ZeroBone** [comment]
My knoledge of the supercell api has become a bit outdated because I was working with it 2 years ago last time. So I am not familiar with the latest developments, sorry. As I understand, the question raised in this pull request is essentially whether we should update the api endpoint from V1 to V2. If the new V2 api is backwards-compatible with V1 or is at least consistent with the documentation, then I think this pull request should be merged. What do you think about this @thispsj? Does the entire documentation you contributed make sense with the new endpoint address?

**Comment by thispsj** [comment]
@ZeroBone changing the root url won't affect the current documentation except for the fact that `bindToken` param has being removed from the login endpoint. And the new API contains some new endpoints which we have not documented. So till Supercell does not decide to sunset V1 why not let things be like they're ?

**Comment by ZeroBone** [comment]
Ok

**Pull request closed without merging**
